### ISSUE TITLE
Pages marked as private still visible in the menu

### ISSUE THREAD

**Issue by imme5150** [rbriank/refinerycms_membership#15]
Just making sure I'm not missing something.  I just installed refinerycms 1.0.0

If this is something that already exisits, maybe it's just not compatible w/ refinerycms 1.0.0 ?

If not, I'm happy to build it.  Also thinking there should be an option on the admin/pages/edit to mark the page as for members only.

Thanks,

..Josh..

**Comment by rbriank** [comment]
This is actually intended, at least for my own use.  Users can see the private entries in the menu, and when they click on them, are asked to sign up/login.

**Comment by gpinkham** [comment]
Curious..  what/where is that controls redirecting them to the sign in page?  Trying to see if I can reuse that logic to hide/show a section of a page..     I want to show/hide a download link based on being a member or not.. 
thanks!
Gary

**Comment by rbriank** [comment]
It's in the lib folder of the engine.
