### ISSUE TITLE
not sure if it's working.. no "new user" 

### ISSUE THREAD

**Issue by gpinkham** [rbriank/refinerycms_membership#16]
ok.. maybe this is a mis configuration or something but I installed..   I set up the :id => 3 role..   I can see the memberships tab in the admin area and I see the user_roles 9with no users) and the pages sub tabs..  I can set which pages are secure to members..  But I don't know how to create a new member..    Am I supposed to include my own custom link on the main site?   is there not a "new" button on the admin area?   Sorry for the noob question..   I'd like to use this and add in a subscription payment through paypal for the members..   so very excited to get this working so I can finish the paypal part.. 

thanks!
Gary

**Comment by rbriank** [comment]
It doesn't have a create users via admin.  You have to assign the user role
to the user via your own code.

B

**Comment by gpinkham** [comment]
ok.. I see a form for new user where does that get called from?   I had assumed there would be a new user registration but I can't seem to find the url to use to include in the login form..   thanks!

**Comment by rbriank** [comment]
It ties into refineries user sign up.

B

**Comment by gpinkham** [comment]
ok.. well I must have that wrong somewhere too as I only get prompted for login.. there is no "signup" link..    hmmm

**Comment by rbriank** [comment]
If you run rake routes, do you see this:

new_user_registration GET    /registrations/register(.:format)
{:action=>"new", :controller=>"registrations"}

B

**Comment by gpinkham** [comment]
ok. I do see that..    couple of odd issues..    trying /users/register forwards me to the login page.. so I can never actually register without logging in first.. :-)    and second I created a user manually in the admin section..  assigned them the member role (and removed the refinery role)..   I logged in with this account and get forwarded to the "dashboard" section of the refinery admin (/refinery)..    that's not good as I was trying to access my members only section of the live site (/videos)..    I will continue to play with this..  maybe I have something configured wrong..  

Thanks
Gary

For the record.. I had to change the superuser can assign roles setting to true to see the roles check boxes on the user edit page in the admin section..

**Comment by rbriank** [comment]
Gary,

If you create a user via the admin section, they get an admin role assigned.

B

**Comment by gpinkham** [comment]
I had removed the refinery role from the user.    so the only role they had was "member"..    Or at least that's what the UI showed.    I'll double check in the console..  

thanks again!
Gary

**Comment by gpinkham** [comment]
verified in the console the user only has the member role..    so I guess the reality of it is I'm not sure what the expected functionality from the built in register/login and the added features of the membership engine are..  So i just don't if it's functional or broken..   time to do some digging into the refinery tests I guess..  :-)  

thanks again for the help!
Gary

PS.  I'm liking some of what i think is in the engine.. Like the approval step..  gives me a place to extend it and add in my payment hook so the membership is automatically approved based on the success of a credit card transaction..  awesome! :-)

**Comment by rbriank** [comment]
Gary,

I wrote it with paypal integration for payments, but removed it to keep the
engine generic.

B

**Comment by gpinkham** [comment]
well that's good to know.    So shouldn't be too hard for a newbie like me to get that in there! :-)    Thanks

**Comment by gpinkham** [comment]
ok so I just relooked at the "rake routes" command you mentioned a few messages ago.. I don't have that same route.    I have this:

new_user_registration GET    /users/register(.:format)                       {:action=>"new", :controller=>"users"}

you're expected route had /registrations/register and the controller was "registrations"..   Is that supposed to come with the memberships engine?    I don't seem to have that route..   And I do not have a registrations controller in the membership engine code..     By the way..   I'm using the latest refinery (1.0.0)..  If that makes a difference.. 

thanks again
Gary

**Comment by rbriank** [comment]
I haven't done anything with one yet.  I wonder if there are some changes
causing problems.

B

**Comment by gpinkham** [comment]
they did switch to devise for auth (not sure when) so maybe that's causing some of the issues..  I have new users being created using the /members/new URL..   I added a ActiveMerchant integration to the MembersController and now payments are processed and the member is automagically activated.     The issue I am tackling now is the redirect after login.   when I try to access the "member secured" page I see the regular Refinery Login page which then redirects me to the admin area Dashboard (which is empty as the member doesn't have permission)..      I think I need to change the Refinery Authentication UsersController's redirect method..  Will try.. Hoping to have a demoable version of this for an interview tomorrow.. :-)

**Comment by rbriank** [comment]
I'd like to add you to my professional network on LinkedIn.
- Brian

Brian  Kierstead
Information Technology and Services Professional
Ontario, Canada

Confirm that you know Brian  Kierstead:
https://www.linkedin.com/e/5y0oq8-gui8q831-48/isd/4773961386/j6FvxqFc/?hs=false&tok=3snJC3ECSJM4Y1

## 

You are receiving Invitation to Connect emails. Click to unsubscribe:
http://www.linkedin.com/e/5y0oq8-gui8q831-48/hHccXBEKeSzYCbZmj8EllkaMGdo3t-oqJs1ccHPEZTFytjuut-ylRvNy7Od3C-8XJKYR92JE7OIM2nLup4sRRLWWe3a0C2zwiWHnqNd/goo/reply%2Bi-1049438-e72bf55f74dc962f93d1a2705edc5fad48f39bf6%40reply%2Egithub%2Ecom/20061/I1659929382_1/?hs=false&tok=1hr3O3OwuJM4Y1

(c) 2011 LinkedIn Corporation. 2029 Stierlin Ct, Mountain View, CA 94043, USA.

**Comment by carpe171** [comment]
Hi Gary,

I'm having trouble setting this engine up.  Could you give me a clue on how you went about setting up your controllers and views?

Thanks,

Wade
