### ISSUE TITLE
Can't find role assignment

### ISSUE THREAD

**Issue by utgarda** [rbriank/refinerycms_membership#2]
Hi! Thanks for the engine, hope you can also hint me about how to use it :)

Put it to Gemfile ( though it doesn't seem necessary, cause it's not deployed anywhere? )
then run 
    rails generate refinerycms_memberships
    rake db:migrate
After that my Users management page looks pretty much the same - creating or editing users I can't see anything about roles.

Also, I don't get how to deal with Heroku, cause they don't let you upload your local gemfiles, they want it in a valid repo. But first I'd like to learn using it locally =)

**Comment by rbriank** [comment]
Hi there,

When I get some time I will add more to it.  Right now the best thing to do is to stick it in
vendor/engines and then reference it in your Gemfile as such:

gem 'refinerycms-memberships', '1.0', :path => 'vendor/engines', :require => 'memberships'

**Comment by utgarda** [comment]
Yup, tried that, got this:
    > rake db:migrate
    ...
    rake aborted! 
    uninitialized constant Memberships::Application

Did I miss something else?

**Comment by rbriank** [comment]
I'm not sure.  I will try and spend some time on this soon.  I'm getting killed with client work ATM.
