### ISSUE TITLE
Memberships engine for Refinery CMS 2.0.3

### ISSUE THREAD

**Issue by phane** [rbriank/refinerycms_membership#29]
I have a problem with install Memberships engine

I cloned the Memberships engine repo into vendor/engines/refinerycms-memberships

<pre>`-----vendor
 |     `-----assets
 |      |     `-----javascripts
 |      |     `-----stylesheets
 |     `-----engines
 |      |     `-----refinerycms-memberships
 |      |      |     `-----app
 |      |      |      |     `-----controllers
 |      |      |      |      |     `-----admin
 |      |      |      |     `-----mailers
 |      |      |      |     `-----models
 |      |      |      |     `-----views
 |      |      |      |      |     `-----admin
 |      |      |      |      |      |     `-----memberships
 |      |      |      |      |      |     `-----user_roles
 |      |      |      |      |     `-----members
 |      |      |      |      |     `-----membership_mailer
 |      |      |     `-----config
 |      |      |      |     `-----initializers
 |      |      |      |     `-----locales
 |      |      |     `-----db
 |      |      |      |     `-----migrate
 |      |      |     `-----lib
 |      |      |      |     `-----generators
 |      |      |      |     `-----rails_datatables
 |      |      |     `-----public
 |      |      |      |     `-----images
 |      |      |      |     `-----javascripts
 |      |      |      |     `-----stylesheets
 |      |      |     `-----spec
 |      |      |      |     `-----controllers
 |      |      |      |      |     `-----admin
 |      |      |      |     `-----mailers
 |      |      |      |     `-----models
 |      |      |      |     `-----support
 |     `-----plugins
</pre>

I added this line to the Gemfile file

<pre>gem 'refinerycms-memberships', '1.0', :path => 'vendor/engines'</pre>

I used 

<pre>bundle install</pre>

<pre>
Using rake (0.9.2.2) 
Using i18n (0.6.0) 
Using multi_json (1.2.0) 
Using activesupport (3.2.3) 
Using builder (3.0.0) 
Using activemodel (3.2.3) 
Using erubis (2.7.0) 
Using journey (1.0.3) 
Using rack (1.4.1) 
Using rack-cache (1.2) 
Using rack-test (0.6.1) 
Using hike (1.2.1) 
Using tilt (1.3.3) 
Using sprockets (2.1.2) 
Using actionpack (3.2.3) 
Using mime-types (1.18) 
Using polyglot (0.3.3) 
Using treetop (1.4.10) 
Using mail (2.4.4) 
Using actionmailer (3.2.3) 
Using arel (3.0.2) 
Using tzinfo (0.3.32) 
Using activerecord (3.2.3) 
Using activeresource (3.2.3) 
Using acts_as_indexed (0.7.8) 
Using awesome_nested_set (2.1.2) 
Using babosa (0.3.7) 
Using bcrypt-ruby (3.0.1) 
Using bundler (1.1.3) 
Using highline (1.6.11) 
Using net-ssh (2.3.0) 
Using net-scp (1.0.4) 
Using net-sftp (2.0.5) 
Using net-ssh-gateway (1.1.0) 
Using capistrano (2.11.2) 
Using coffee-script-source (1.2.0) 
Using execjs (1.3.0) 
Using coffee-script (2.2.0) 
Using rack-ssl (1.3.2) 
Using json (1.6.6) 
Using rdoc (3.12) 
Using thor (0.14.6) 
Using railties (3.2.3) 
Using coffee-rails (3.2.2) 
Using orm_adapter (0.0.7) 
Using warden (1.1.1) 
Using devise (2.0.4) 
Using dragonfly (0.9.11) 
Using friendly_id (4.0.4) 
Using paper_trail (2.6.3) 
Using globalize3 (0.2.0) 
Using jquery-rails (2.0.1) 
Using pg (0.13.2) 
Using rails (3.2.3) 
Using sass (3.1.15) 
Using sass-rails (3.2.5) 
Using truncate_html (0.5.4) 
Using uglifier (1.2.4) 
Using will_paginate (3.0.3) 
Using refinerycms-core (2.0.3) 
Using refinerycms-authentication (2.0.3) 
Using refinerycms-dashboard (2.0.3) 
Using refinerycms-images (2.0.3) 
Using seo_meta (1.3.0) 
Using refinerycms-pages (2.0.3) 
Using refinerycms-resources (2.0.3) 
Using refinerycms (2.0.3) 
Using routing-filter (0.3.0) 
Using refinerycms-i18n (2.0.0) 
Using refinerycms-memberships (1.0) from source at vendor/engines 
Using refinerycms-settings (2.0.1)
</pre>

I use 

<pre>rails generate refinerycms_memberships</pre>

but 

<pre>
/Users/stephane/.rvm/gems/ruby-1.9.3-p125@global/gems/bundler-1.1.3/lib/bundler/runtime.rb:74:in `require': cannot load such file -- refinerycms/memberships (LoadError)
    from /Users/stephane/.rvm/gems/ruby-1.9.3-p125@global/gems/bundler-1.1.3/lib/bundler/runtime.rb:74:in `rescue in block in require'
    from /Users/stephane/.rvm/gems/ruby-1.9.3-p125@global/gems/bundler-1.1.3/lib/bundler/runtime.rb:62:in `block in require'
    from /Users/stephane/.rvm/gems/ruby-1.9.3-p125@global/gems/bundler-1.1.3/lib/bundler/runtime.rb:55:in `each'
    from /Users/stephane/.rvm/gems/ruby-1.9.3-p125@global/gems/bundler-1.1.3/lib/bundler/runtime.rb:55:in `require'
    from /Users/stephane/.rvm/gems/ruby-1.9.3-p125@global/gems/bundler-1.1.3/lib/bundler.rb:119:in `require'
    from /Volumes/MacData/appnew.com/sites/appnew/config/application.rb:7:in `<top (required)>'
    from /Users/stephane/.rvm/gems/ruby-1.9.3-p125@refinery2.0.3/gems/railties-3.2.3/lib/rails/commands.rb:24:in `require'
    from /Users/stephane/.rvm/gems/ruby-1.9.3-p125@refinery2.0.3/gems/railties-3.2.3/lib/rails/commands.rb:24:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
</pre>

Could you help me ?

**Comment by williscool** [comment]
im having almost literally the identical issue with the multisite plugin 

https://github.com/YuzuTen/refinerycms-multisite

**Comment by rteeuwen** [comment]
@williscool did you find a solution to your problem? I've got the same problem with the multisite plugin.

**Comment by williscool** [comment]
long story short it means which ever version you are installing hasn't been updated to be a refinery 2.0 engine properly.

I tried really hard to do it with the muiltsite plugin but had no luck.

Let me know if you do

**Comment by phane** [comment]
Memberships engine  only compatible with Refinery 2.0, i don't have find solution
